import { buildLandingDesignStyle } from "@/app/components/crm-template-editor/landing-designs/build-landing-design";
import type { LandingDesignCatalogEntry } from "@/app/components/crm-template-editor/landing-designs/build-landing-design";
import type {
  LandingDesignOptionRow,
  LandingDesignStyle,
} from "@/app/components/crm-template-editor/landing-designs/types";

/**
 * Single source of truth for landing designs.
 * To add a design: append one row here (preset + colors + copy).
 */
export const LANDING_DESIGN_CATALOG = [
  {
    id: "classic_offer",
    swatchKind: "lavender",
    mode: "light",
    accent: "violet",
    label: "Classic Offer",
    description: "Soft lavender with gradient CTA — clean and modern.",
    backgroundDefault: "#F8F7FF",
    primary: "#5B5FEF",
    secondary: "#7C3AED",
    eyebrow: "Exclusive offer",
    trustLine: "Secure checkout · No commitment required",
  },
  {
    id: "midnight_glow",
    swatchKind: "dark",
    mode: "dark",
    accent: "cyan",
    label: "Midnight Glow",
    description: "Dark background with bright accent — bold nightlife vibe.",
    backgroundDefault: "#0F172A",
    primary: "#22D3EE",
    secondary: "#6366F1",
    eyebrow: "Members only",
    trustLine: "Encrypted checkout · Cancel anytime",
  },
  {
    id: "sunset_warm",
    swatchKind: "warm",
    mode: "light",
    accent: "orange",
    label: "Sunset Warm",
    description: "Amber and coral tones — great for restaurants.",
    backgroundDefault: "#FFF7ED",
    primary: "#EA580C",
    secondary: "#DC2626",
    eyebrow: "Tonight only",
    trustLine: "Book in seconds · Free to join",
  },
  {
    id: "forest_fresh",
    swatchKind: "green",
    mode: "light",
    accent: "emerald",
    label: "Forest Fresh",
    description: "Natural greens — wellness and organic brands.",
    backgroundDefault: "#F0FDF4",
    primary: "#059669",
    secondary: "#0D9488",
    eyebrow: "Limited spots",
    trustLine: "Natural ingredients · Satisfaction guaranteed",
  },
  {
    id: "ocean_breeze",
    swatchKind: "blue",
    mode: "light",
    accent: "sky",
    label: "Ocean Breeze",
    description: "Cool blues and teals — fresh and trustworthy.",
    backgroundDefault: "#EFF6FF",
    primary: "#2563EB",
    secondary: "#0891B2",
    eyebrow: "Special deal",
    trustLine: "Trusted by 10,000+ customers",
  },
  {
    id: "minimal_mono",
    swatchKind: "mono",
    mode: "mono",
    label: "Minimal Mono",
    description: "Black and white — sharp, editorial simplicity.",
    backgroundDefault: "#FFFFFF",
    primary: "#18181B",
    secondary: "#3F3F46",
    eyebrow: "New",
    trustLine: "Simple checkout · No hidden fees",
    ctaShadowOpacity: 0.15,
  },
  {
    id: "rose_elegance",
    swatchKind: "rose",
    mode: "light",
    accent: "rose",
    label: "Rose Elegance",
    description: "Blush and rose — beauty, events, and luxury.",
    backgroundDefault: "#FFF1F2",
    primary: "#E11D48",
    secondary: "#DB2777",
    eyebrow: "VIP access",
    trustLine: "Premium experience · Limited availability",
  },
  {
    id: "bold_contrast",
    swatchKind: "contrast",
    mode: "dark",
    accent: "contrast",
    label: "Bold Contrast",
    description: "High-impact yellow on black — loud and energetic.",
    backgroundDefault: "#09090B",
    primary: "#FACC15",
    secondary: "#EAB308",
    eyebrow: "Act fast",
    trustLine: "Limited time · While supplies last",
    ctaShadowOpacity: 0.35,
  },
  {
    id: "golden_hour",
    swatchKind: "gold",
    mode: "dark",
    accent: "amber",
    label: "Golden Hour",
    description: "Gold on deep charcoal — premium membership feel.",
    backgroundDefault: "#1C1917",
    primary: "#D4AF37",
    secondary: "#B8860B",
    eyebrow: "Premium",
    trustLine: "White-glove service · Exclusive benefits",
  },
  {
    id: "soft_cream",
    swatchKind: "cream",
    mode: "light",
    accent: "amber",
    label: "Soft Cream",
    description: "Warm paper tones — calm, readable, hospitality.",
    backgroundDefault: "#FAF8F5",
    primary: "#92400E",
    secondary: "#B45309",
    eyebrow: "Welcome offer",
    trustLine: "Family friendly · Easy reservation",
    ctaShadowOpacity: 0.2,
  },
  {
    id: "plum_luxe",
    swatchKind: "plum",
    mode: "dark",
    accent: "plum",
    label: "Plum Luxe",
    description: "Deep purple luxury — spas, wine bars, and boutiques.",
    backgroundDefault: "#1E1033",
    primary: "#A855F7",
    secondary: "#D946EF",
    eyebrow: "Private access",
    trustLine: "Curated experience · Invite only",
  },
  {
    id: "coral_pop",
    swatchKind: "coral",
    mode: "light",
    accent: "coral",
    label: "Coral Pop",
    description: "Bright coral and pink — fun campaigns and promos.",
    backgroundDefault: "#FFF5F7",
    primary: "#F472B6",
    secondary: "#FB7185",
    eyebrow: "Flash sale",
    trustLine: "Join in 30 seconds · No spam",
  },
  {
    id: "arctic_mist",
    swatchKind: "slate",
    mode: "light",
    accent: "slate",
    label: "Arctic Mist",
    description: "Cool gray minimal — SaaS, tech, and professional services.",
    backgroundDefault: "#F8FAFC",
    primary: "#475569",
    secondary: "#64748B",
    eyebrow: "Early access",
    trustLine: "Enterprise-grade security · GDPR ready",
  },
  {
    id: "electric_pulse",
    swatchKind: "electric",
    mode: "dark",
    accent: "electric",
    label: "Electric Pulse",
    description: "Neon fuchsia on violet — events, music, and nightlife.",
    backgroundDefault: "#1E0B3A",
    primary: "#E879F9",
    secondary: "#8B5CF6",
    eyebrow: "Live now",
    trustLine: "Instant confirmation · Mobile tickets",
  },
  {
    id: "sage_calm",
    swatchKind: "sage",
    mode: "light",
    accent: "sage",
    label: "Sage Calm",
    description: "Muted sage green — yoga, wellness, and calm brands.",
    backgroundDefault: "#F7FEE7",
    primary: "#65A30D",
    secondary: "#16A34A",
    eyebrow: "Wellness week",
    trustLine: "Mindful signup · Unsubscribe anytime",
  },
  {
    id: "wine_velvet",
    swatchKind: "wine",
    mode: "dark",
    accent: "wine",
    label: "Wine Velvet",
    description: "Rich burgundy — fine dining and wine clubs.",
    backgroundDefault: "#2A0A12",
    primary: "#FB7185",
    secondary: "#BE123C",
    eyebrow: "Cellar club",
    trustLine: "Sommelier picks · Members save 15%",
  },
  {
    id: "candy_shop",
    swatchKind: "candy",
    mode: "light",
    accent: "candy",
    label: "Candy Shop",
    description: "Playful fuchsia — bakeries, treats, and family brands.",
    backgroundDefault: "#FDF4FF",
    primary: "#C026D3",
    secondary: "#EC4899",
    eyebrow: "Sweet deal",
    trustLine: "Free gift on signup · Limited batches",
  },
  {
    id: "coastal_sand",
    swatchKind: "teal",
    mode: "light",
    accent: "teal",
    label: "Coastal Sand",
    description: "Teal and sand — beach clubs, resorts, and travel.",
    backgroundDefault: "#F0FDFA",
    primary: "#0D9488",
    secondary: "#0284C7",
    eyebrow: "Season pass",
    trustLine: "Book your stay · Best price guarantee",
  },
  {
    id: "graphite_pro",
    swatchKind: "indigo",
    mode: "dark",
    accent: "graphite",
    label: "Graphite Pro",
    description: "Slate blue dark — B2B, finance, and consulting.",
    backgroundDefault: "#0F172A",
    primary: "#60A5FA",
    secondary: "#38BDF8",
    eyebrow: "Pro plan",
    trustLine: "SOC 2 compliant · Dedicated support",
  },
  {
    id: "berry_burst",
    swatchKind: "berry",
    mode: "light",
    accent: "berry",
    label: "Berry Burst",
    description: "Bold berry red — retail drops and limited releases.",
    backgroundDefault: "#FFF1F2",
    primary: "#DC2626",
    secondary: "#E11D48",
    eyebrow: "Drop live",
    trustLine: "One-click checkout · Ships fast",
  },
  {
    id: "mint_frost",
    swatchKind: "mint",
    mode: "light",
    accent: "mint",
    label: "Mint Frost",
    description: "Icy mint cyan — health, fitness, and fresh starts.",
    backgroundDefault: "#ECFEFF",
    primary: "#0891B2",
    secondary: "#06B6D4",
    eyebrow: "Fresh start",
    trustLine: "7-day trial · Cancel anytime",
  },
  {
    id: "evergreen_night",
    swatchKind: "forest",
    mode: "dark",
    accent: "forest",
    label: "Evergreen Night",
    description: "Deep forest green — outdoor, eco, and adventure brands.",
    backgroundDefault: "#052E16",
    primary: "#4ADE80",
    secondary: "#22C55E",
    eyebrow: "Trail pass",
    trustLine: "Eco-certified · Plant a tree per signup",
  },
] as const satisfies readonly LandingDesignCatalogEntry[];

export type LandingDesign = (typeof LANDING_DESIGN_CATALOG)[number]["id"];

export const landingDesignStyles = Object.fromEntries(
  LANDING_DESIGN_CATALOG.map((entry) => [
    entry.id,
    buildLandingDesignStyle(entry),
  ]),
) as Record<LandingDesign, LandingDesignStyle>;

export const LANDING_DESIGN_OPTIONS: LandingDesignOptionRow[] =
  LANDING_DESIGN_CATALOG.map((entry) => ({
    value: entry.id,
    label: entry.label,
    description: entry.description,
  }));
